version: "3"
services:
    hahn:
        build:
          context: ../
          dockerfile: Hahn.ApplicationProcess.February2021.Web/Dockerfile
          args:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 8080:80