//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hahn.Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hahn.Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        public static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot handle the request..
        /// </summary>
        public static string _503 {
            get {
                return ResourceManager.GetString("503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add asset.
        /// </summary>
        public static string AddAsset {
            get {
                return ResourceManager.GetString("AddAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was successfully saved..
        /// </summary>
        public static string AssetCreated {
            get {
                return ResourceManager.GetString("AssetCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the following data: .
        /// </summary>
        public static string CheckErrors {
            get {
                return ResourceManager.GetString("CheckErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Department.
        /// </summary>
        public static string CountryOfDepartment {
            get {
                return ResourceManager.GetString("CountryOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        public static string Department0 {
            get {
                return ResourceManager.GetString("Department0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store 1.
        /// </summary>
        public static string Department1 {
            get {
                return ResourceManager.GetString("Department1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store 2.
        /// </summary>
        public static string Department2 {
            get {
                return ResourceManager.GetString("Department2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store 3.
        /// </summary>
        public static string Department3 {
            get {
                return ResourceManager.GetString("Department3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance station.
        /// </summary>
        public static string Department4 {
            get {
                return ResourceManager.GetString("Department4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address of Department.
        /// </summary>
        public static string EmailAddressOfDepartment {
            get {
                return ResourceManager.GetString("EmailAddressOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t process sended request. More information:.
        /// </summary>
        public static string Error400Message {
            get {
                return ResourceManager.GetString("Error400Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string Error400Title {
            get {
                return ResourceManager.GetString("Error400Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to authenticate first, before try to make this request. More information:.
        /// </summary>
        public static string Error401Message {
            get {
                return ResourceManager.GetString("Error401Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Error401Title {
            get {
                return ResourceManager.GetString("Error401Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have necessary access level to perform this operation. More information:.
        /// </summary>
        public static string Error403Message {
            get {
                return ResourceManager.GetString("Error403Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Error403Title {
            get {
                return ResourceManager.GetString("Error403Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request returned with no result. More information:.
        /// </summary>
        public static string Error404Message {
            get {
                return ResourceManager.GetString("Error404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string Error404Title {
            get {
                return ResourceManager.GetString("Error404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API request may be malformed. More information:.
        /// </summary>
        public static string Error405Message {
            get {
                return ResourceManager.GetString("Error405Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not allowed.
        /// </summary>
        public static string Error405Title {
            get {
                return ResourceManager.GetString("Error405Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time, request can&apos;t be processed because a server error. Please, try again later. More information:.
        /// </summary>
        public static string Error500Message {
            get {
                return ResourceManager.GetString("Error500Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string Error500Title {
            get {
                return ResourceManager.GetString("Error500Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, complete this field..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must have at least five charcters..
        /// </summary>
        public static string InvalidAssetName {
            get {
                return ResourceManager.GetString("InvalidAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name not found..
        /// </summary>
        public static string InvalidCountryName {
            get {
                return ResourceManager.GetString("InvalidCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid department value..
        /// </summary>
        public static string InvalidDepartment {
            get {
                return ResourceManager.GetString("InvalidDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date entered is invalid or is more than one year old..
        /// </summary>
        public static string InvalidPurchaseDate {
            get {
                return ResourceManager.GetString("InvalidPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Broken.
        /// </summary>
        public static string IsBroken {
            get {
                return ResourceManager.GetString("IsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info:.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New asset.
        /// </summary>
        public static string NewAsset {
            get {
                return ResourceManager.GetString("NewAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any asset..
        /// </summary>
        public static string NoAssetsFound {
            get {
                return ResourceManager.GetString("NoAssetsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It could not be validated..
        /// </summary>
        public static string NotValidated {
            get {
                return ResourceManager.GetString("NotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body cannot be null..
        /// </summary>
        public static string NullBody {
            get {
                return ResourceManager.GetString("NullBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, contact the site admin..
        /// </summary>
        public static string PleaseContactTheAdmin {
            get {
                return ResourceManager.GetString("PleaseContactTheAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date (in UTC).
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this asset?.
        /// </summary>
        public static string RemoveAssetMessage {
            get {
                return ResourceManager.GetString("RemoveAssetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset the form?.
        /// </summary>
        public static string ResetFormMessage {
            get {
                return ResourceManager.GetString("ResetFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
